### ISSUE TITLE
It works?

### ISSUE THREAD

**Issue by rikcage** [eLFuvo/yii2-import-wizard#1]
Does this extension work? Or is it in development?

**Comment by eLFuvo** [comment]
This extension was tested on few projects. Stil hasn't stable version because need more tests.

**Comment by rikcage** [comment]
It doesn't work for me.
The first line in being processed and no finished it.
And I not see any errors.
May be problem in "queue"?
I set settings as in https://github.com/eLFuvo/yii2-import-wizard/blob/master/tests/app/config/common.php
```
        'queue' => [
            'class' => \yii\queue\file\Queue::class,
            'path' => '@runtime/queue',
        ],

```
also I set it as
```
        'queue' => [
            'class' => \yii\queue\db\Queue::class,
            'db' => 'db', // DB connection component or its config 
            'tableName' => '{{%queue}}', // Table name
            'channel' => 'default', // Queue channel key
            'mutex' => \yii\mutex\MysqlMutex::class, // Mutex used to sync queries
        ],

```
but i not see any progress in queue, i not see any step.

**Comment by eLFuvo** [comment]
There is you can see that queue job is runned mannualy
https://github.com/eLFuvo/yii2-import-wizard/blob/master/tests/functional/UploadImportFileCest.php#L81

use this command for queue listen and run jobs in background
```sh
 /usr/local/bin/php /var/www/html/project/framework/yii queue/listen 5 --verbose=1 --isolate=1 --color=0 &
```
